use std::fmt::Display;
use std::str::FromStr;
use crate::PKError;

/// Struct representing a hand combination symbol, aka AKs or 99+. A subset of strings that
/// can represent a hand combination.
#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct HCSymbol(String);

impl HCSymbol {
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Display for HCSymbol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", &self.0.to_string())
    }
}

impl FromStr for HCSymbol {
    type Err = PKError;

    fn from_str(raw: &str) -> Result<Self, Self::Err> {
        let s = match raw.trim().to_ascii_uppercase().as_str() {
            "AA" => "AA",
            "KK" => "KK",
            "QQ" => "QQ",
            "JJ" => "JJ",
            "TT" => "TT",
            "99" => "99",
            "88" => "88",
            "77" => "77",
            "66" => "66",
            "55" => "55",
            "44" => "44",
            "33" => "33",
            "22" => "22",

            "AK" => "AK",
            "AKS" => "AKs",
            "AKO" => "AKo",
            "AQ" => "AQ",
            "AQS" => "AQs",
            "AQO" => "AQo",
            "AJ" => "AJ",
            "AJS" => "AJs",
            "AJO" => "AJo",
            "AT" => "AT",
            "ATS" => "ATs",
            "ATO" => "ATo",
            "A9" => "A9",
            "A9S" => "A9s",
            "A9O" => "A9o",
            "A8" => "A8",
            "A8S" => "A8s",
            "A8O" => "A8o",
            "A7" => "A7",
            "A7S" => "A7s",
            "A7O" => "A7o",
            "A6" => "A6",
            "A6S" => "A6s",
            "A6O" => "A6o",
            "A5" => "A5",
            "A5S" => "A5s",
            "A5O" => "A5o",
            "A4" => "A4",
            "A4S" => "A4s",
            "A4O" => "A4o",
            "A3" => "A3",
            "A3S" => "A3s",
            "A3O" => "A3o",
            "A2" => "A2",
            "A2S" => "A2s",
            "A2O" => "A2o",

            "KQ" => "KQ",
            "KQS" => "KQs",
            "KQO" => "KQo",
            "KJ" => "KJ",
            "KJS" => "KJs",
            "KJO" => "KJo",
            "KT" => "KT",
            "KTS" => "KTs",
            "KTO" => "KTo",
            "K9" => "K9",
            "K9S" => "K9s",
            "K9O" => "K9o",
            "K8" => "K8",
            "K8S" => "K8s",
            "K8O" => "K8o",
            "K7" => "K7",
            "K7S" => "K7s",
            "K7O" => "K7o",
            "K6" => "K6",
            "K6S" => "K6s",
            "K6O" => "K6o",
            "K5" => "K5",
            "K5S" => "K5s",
            "K5O" => "K5o",
            "K4" => "K4",
            "K4S" => "K4s",
            "K4O" => "K4o",
            "K3" => "K3",
            "K3S" => "K3s",
            "K3O" => "K3o",
            "K2" => "K2",
            "K2S" => "K2s",
            "K2O" => "K2o",

            "QJ" => "QJ",
            "QJS" => "QJs",
            "QJO" => "QJo",
            "QT" => "QT",
            "QTS" => "QTs",
            "QTO" => "QTo",
            "Q9" => "Q9",
            "Q9S" => "Q9s",
            "Q9O" => "Q9o",
            "Q8" => "Q8",
            "Q8S" => "Q8s",
            "Q8O" => "Q8o",
            "Q7" => "Q7",
            "Q7S" => "Q7s",
            "Q7O" => "Q7o",
            "Q6" => "Q6",
            "Q6S" => "Q6s",
            "Q6O" => "Q6o",
            "Q5" => "Q5",
            "Q5S" => "Q5s",
            "Q5O" => "Q5o",
            "Q4" => "Q4",
            "Q4S" => "Q4s",
            "Q4O" => "Q4o",
            "Q3" => "Q3",
            "Q3S" => "Q3s",
            "Q3O" => "Q3o",
            "Q2" => "Q2",
            "Q2S" => "Q2s",
            "Q2O" => "Q2o",
            "JT" => "JT",
            "JTS" => "JTs",
            "JTO" => "JTo",
            "J9" => "J9",
            "J9S" => "J9s",
            "J9O" => "J9o",
            "J8" => "J8",
            "J8S" => "J8s",
            "J8O" => "J8o",
            "J7" => "J7",
            "J7S" => "J7s",
            "J7O" => "J7o",
            "J6" => "J6",
            "J6S" => "J6s",
            "J6O" => "J6o",
            "J5" => "J5",
            "J5S" => "J5s",
            "J5O" => "J5o",
            "J4" => "J4",
            "J4S" => "J4s",
            "J4O" => "J4o",
            "J3" => "J3",
            "J3S" => "J3s",
            "J3O" => "J3o",
            "J2" => "J2",
            "J2S" => "J2s",
            "J2O" => "J2o",
            "T9" => "T9",
            "T9S" => "T9s",
            "T9O" => "T9o",
            "T8" => "T8",
            "T8S" => "T8s",
            "T8O" => "T8o",
            "T7" => "T7",
            "T7S" => "T7s",
            "T7O" => "T7o",
            "T6" => "T6",
            "T6S" => "T6s",
            "T6O" => "T6o",
            "T5" => "T5",
            "T5S" => "T5s",
            "T5O" => "T5o",
            "T4" => "T4",
            "T4S" => "T4s",
            "T4O" => "T4o",
            "T3" => "T3",
            "T3S" => "T3s",
            "T3O" => "T3o",
            "T2" => "T2",
            "T2S" => "T2s",
            "T2O" => "T2o",
            "98" => "98",
            "98S" => "98s",
            "98O" => "98o",
            "97" => "97",
            "97S" => "97s",
            "97O" => "97o",
            "96" => "96",
            "96S" => "96s",
            "96O" => "96o",
            "95" => "95",
            "95S" => "95s",
            "95O" => "95o",
            "94" => "94",
            "94S" => "94s",
            "94O" => "94o",
            "93" => "93",
            "93S" => "93s",
            "93O" => "93o",
            "92" => "92",
            "92S" => "92s",
            "92O" => "92o",
            "87" => "87",
            "87S" => "87s",
            "87O" => "87o",
            "86" => "86",
            "86S" => "86s",
            "86O" => "86o",
            "85" => "85",
            "85S" => "85s",
            "85O" => "85o",
            "84" => "84",
            "84S" => "84s",
            "84O" => "84o",
            "83" => "83",
            "83S" => "83s",
            "83O" => "83o",
            "82" => "82",
            "82S" => "82s",
            "82O" => "82o",
            "76" => "76",
            "76S" => "76s",
            "76O" => "76o",
            "75" => "75",
            "75S" => "75s",
            "75O" => "75o",
            "74" => "74",
            "74S" => "74s",
            "74O" => "74o",
            "73" => "73",
            "73S" => "73s",
            "73O" => "73o",
            "72" => "72",
            "72S" => "72s",
            "72O" => "72o",
            "65" => "65",
            "65S" => "65s",
            "65O" => "65o",
            "64" => "64",
            "64S" => "64s",
            "64O" => "64o",
            "63" => "63",
            "63S" => "63s",
            "63O" => "63o",
            "62" => "62",
            "62S" => "62s",
            "62O" => "62o",
            "54" => "54",
            "54S" => "54s",
            "54O" => "54o",
            "53" => "53",
            "53S" => "53s",
            "53O" => "53o",
            "52" => "52",
            "52S" => "52s",
            "52O" => "52o",
            "43" => "43",
            "43S" => "43s",
            "43O" => "43o",
            "42" => "42",
            "42S" => "42s",
            "42O" => "42o",
            "32" => "32",
            "32S" => "32s",
            "32O" => "32o",

            // Multis
            "KK+" => "KK+", // Multi pairs
            "QQ+" => "QQ+",
            "JJ+" => "JJ+",
            "TT+" => "TT+",
            "99+" => "99+",
            "88+" => "88+",
            "77+" => "77+",
            "66+" => "66+",
            "55+" => "55+",
            "44+" => "44+",
            "33+" => "33+",
            "22+" => "22+",

            "KQ+" => "KQ+",
            "QJ+" => "QJ+",
            "JT+" => "JT+",
            "T9+" => "T9+",
            "98+" => "98+",
            "87+" => "87+",
            "76+" => "76+",
            "65+" => "65+",
            "54+" => "54+",
            "43+" => "43+",
            "32+" => "32+",

            "AQ+" => "AQ+", // Multi disconnected (includes connected top aka AK)
            "AJ+" => "AJ+",
            "AT+" => "AT+",
            "A9+" => "A9+",
            "A8+" => "A8+",
            "A7+" => "A7+",
            "A6+" => "A6+",
            "A5+" => "A5+",
            "A4+" => "A4+",
            "A3+" => "A3+",
            "A2+" => "Ax",
            "AX" => "Ax",


            "KJ+" => "KJ+",
            "KT+" => "KT+",
            "K9+" => "K9+",
            "K8+" => "K8+",
            "K7+" => "K7+",
            "K6+" => "K6+",
            "K5+" => "K5+",
            "K4+" => "K4+",
            "K3+" => "K3+",
            "K2+" => "Kx",
            "KX"  => "Kx",

            "QT+" => "QT+",
            "Q9+" => "Q9+",

            _ => return Err(PKError::InvalidIndex),
        };
            
        Ok(HCSymbol(s.to_string()))
    }
}