# Default state for all rules
default: true

# allow long lines for tables and code blocks
MD013:
  code_blocks: false
  tables: false

# headings must be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1
