[package]
name = "pkcore"
version = "0.0.4"
rust-version = "1.63"
edition = "2021"
authors = ["electronicpanopticon <gaoler@electronicpanopticon.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/ImperialBower/pkcore.git"
homepage = "https://github.com/ImperialBower/pkcore"
exclude = [".github/workflows/*", "examples/*", ".gitignore", "Cargo.lock"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = { version = "1.9.1", features = ["rayon"] }
itertools = "0.10.3"
log = "0.4.17"
rand = "0.8.5"
rayon = "1.5.3"
serde = { version = "1.0.136", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
# wincounter = "0.1.1"

[dev-dependencies]
clap = { version = "4.1.8", features = ["derive", "unicode"] }
elr_primes = "0.1.2"
env_logger = "0.10.0"
rstest = "0.16.0"
