[package]
name = "pkcore"
description = "Prototype core poker library."
version = "0.0.24"
rust-version = "1.91.0"
edition = "2024"
authors = ["electronicpanopticon <gaoler@electronicpanopticon.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/ImperialBower/pkcore.git"
homepage = "https://github.com/ImperialBower/pkcore"
exclude = [".github/workflows/*", "data/*", "docs/*", "examples/*", "generated/old/*", "proto/*", "scripts/*", ".gitignore", "Cargo.lock", "Claude.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bint = "0.1.15"
cardpack = "0.6.9"
bitvec = { version = "1.0.1", features = ["alloc",  "atomic", "std", "serde", "testing" ] }
csv = "1.4"
dotenvy = "0.15"
indexmap = { version = "2.12", features = ["rayon"] }
itertools = "0.14"
log = "0.4"
percent-encoding = "2.3"
pkstate = "0.1.2"
rand = "0.9"
random_name_generator = "0.3.6" 
rayon = "1.11.0"
regex = { version = "1.12", features = [] }
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.28", features = ["derive"] }
strum_macros = "0.28"
tempfile = "3.27"
thousands = "0.2.0"
uuid = { version = "1.22", features = ["serde", "v4"] }
wincounter = "0.1.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusqlite = { version = "0.34", features = ["bundled"] } # 0.35 breaks HUPResult https://github.com/rusqlite/rusqlite/releases#reactions--reaction_button_component-a0702b
termion = "4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom_v2 = { package = "getrandom", version = "0.2", features = ["js"] }
getrandom_v3 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }
uuid = { version = "1.22", features = ["serde", "v4", "js"] }

[dev-dependencies]
assert-struct = "0.4.0"
serde_yaml_bw = "2.5"
clap = { version = "4.6", features = ["derive", "unicode"] }
clap-repl = "0.3.2"
reedline = "0.38"
elr_primes = "0.1.2"
env_logger = "0.11.9"

rstest = "0.26.1"
serde_test = "1.0.177"
testing_logger = "0.1.1"
#ratatui = { version = "0.30", features = ["all-widgets"] }
test-log = "0.2.19"

