[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clippy]
install_crate = "rustfmt"
command = "cargo"
args = ["clippy"]

[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.ayce]
dependencies = [
    "fmt",
    "build",
    "test",
    "clippy"
]

[tasks.default]
alias = "ayce"