use crate::hand_rank::hand_rank::HandRankValue;
use crate::SOK;
use strum::EnumIter;

/// `HandRankClass` represents the more specific type of the five card `PokerHand`.
#[allow(clippy::module_name_repetitions)]
#[derive(Clone, Copy, Debug, EnumIter, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Class {
    RoyalFlush,
    KingHighStraightFlush,
    QueenHighStraightFlush,
    JackHighStraightFlush,
    TenHighStraightFlush,
    NineHighStraightFlush,
    EightHighStraightFlush,
    SevenHighStraightFlush,
    SixHighStraightFlush,
    FiveHighStraightFlush,
    FourAces,
    FourKings,
    FourQueens,
    FourJacks,
    FourTens,
    FourNines,
    FourEights,
    FourSevens,
    FourSixes,
    FourFives,
    FourFours,
    FourTreys,
    FourDeuces,
    AcesOverKings,
    AcesOverQueens,
    AcesOverJacks,
    AcesOverTens,
    AcesOverNines,
    AcesOverEights,
    AcesOverSevens,
    AcesOverSixes,
    AcesOverFives,
    AcesOverFours,
    AcesOverTreys,
    AcesOverDeuces,
    KingsOverAces,
    KingsOverQueens,
    KingsOverJacks,
    KingsOverTens,
    KingsOverNines,
    KingsOverEights,
    KingsOverSevens,
    KingsOverSixes,
    KingsOverFives,
    KingsOverFours,
    KingsOverTreys,
    KingsOverDeuces,
    QueensOverAces,
    QueensOverKings,
    QueensOverJacks,
    QueensOverTens,
    QueensOverNines,
    QueensOverEights,
    QueensOverSevens,
    QueensOverSixes,
    QueensOverFives,
    QueensOverFours,
    QueensOverTreys,
    QueensOverDeuces,
    JacksOverAces,
    JacksOverKings,
    JacksOverQueens,
    JacksOverTens,
    JacksOverNines,
    JacksOverEights,
    JacksOverSevens,
    JacksOverSixes,
    JacksOverFives,
    JacksOverFours,
    JacksOverTreys,
    JacksOverDeuces,
    TensOverAces,
    TensOverKings,
    TensOverQueens,
    TensOverJacks,
    TensOverNines,
    TensOverEights,
    TensOverSevens,
    TensOverSixes,
    TensOverFives,
    TensOverFours,
    TensOverTreys,
    TensOverDeuces,
    NinesOverAces,
    NinesOverKings,
    NinesOverQueens,
    NinesOverJacks,
    NinesOverTens,
    NinesOverEights,
    NinesOverSevens,
    NinesOverSixes,
    NinesOverFives,
    NinesOverFours,
    NinesOverTreys,
    NinesOverDeuces,
    EightsOverAces,
    EightsOverKings,
    EightsOverQueens,
    EightsOverJacks,
    EightsOverTens,
    EightsOverNines,
    EightsOverSevens,
    EightsOverSixes,
    EightsOverFives,
    EightsOverFours,
    EightsOverTreys,
    EightsOverDeuces,
    SevensOverAces,
    SevensOverKings,
    SevensOverQueens,
    SevensOverJacks,
    SevensOverTens,
    SevensOverNines,
    SevensOverEights,
    SevensOverSixes,
    SevensOverFives,
    SevensOverFours,
    SevensOverTreys,
    SevensOverDeuces,
    SixesOverAces,
    SixesOverKings,
    SixesOverQueens,
    SixesOverJacks,
    SixesOverTens,
    SixesOverNines,
    SixesOverEights,
    SixesOverSevens,
    SixesOverFives,
    SixesOverFours,
    SixesOverTreys,
    SixesOverDeuces,
    FivesOverAces,
    FivesOverKings,
    FivesOverQueens,
    FivesOverJacks,
    FivesOverTens,
    FivesOverNines,
    FivesOverEights,
    FivesOverSevens,
    FivesOverSixes,
    FivesOverFours,
    FivesOverTreys,
    FivesOverDeuces,
    FoursOverAces,
    FoursOverKings,
    FoursOverQueens,
    FoursOverJacks,
    FoursOverTens,
    FoursOverNines,
    FoursOverEights,
    FoursOverSevens,
    FoursOverSixes,
    FoursOverFives,
    FoursOverTreys,
    FoursOverDeuces,
    TreysOverAces,
    TreysOverKings,
    TreysOverQueens,
    TreysOverJacks,
    TreysOverTens,
    TreysOverNines,
    TreysOverEights,
    TreysOverSevens,
    TreysOverSixes,
    TreysOverFives,
    TreysOverFours,
    TreysOverDeuces,
    DeucesOverAces,
    DeucesOverKings,
    DeucesOverQueens,
    DeucesOverJacks,
    DeucesOverTens,
    DeucesOverNines,
    DeucesOverEights,
    DeucesOverSevens,
    DeucesOverSixes,
    DeucesOverFives,
    DeucesOverFours,
    DeucesOverTreys,
    AceHighFlush,
    KingHighFlush,
    QueenHighFlush,
    JackHighFlush,
    TenHighFlush,
    NineHighFlush,
    EightHighFlush,
    SevenHighFlush,
    AceHighStraight,
    KingHighStraight,
    QueenHighStraight,
    JackHighStraight,
    TenHighStraight,
    NineHighStraight,
    EightHighStraight,
    SevenHighStraight,
    SixHighStraight,
    FiveHighStraight,
    ThreeAces,
    ThreeKings,
    ThreeQueens,
    ThreeJacks,
    ThreeTens,
    ThreeNines,
    ThreeEights,
    ThreeSevens,
    ThreeSixes,
    ThreeFives,
    ThreeFours,
    ThreeTreys,
    ThreeDeuces,
    AcesAndKings,
    AcesAndQueens,
    AcesAndJacks,
    AcesAndTens,
    AcesAndNines,
    AcesAndEights,
    AcesAndSevens,
    AcesAndSixes,
    AcesAndFives,
    AcesAndFours,
    AcesAndTreys,
    AcesAndDeuces,
    KingsAndQueens,
    KingsAndJacks,
    KingsAndTens,
    KingsAndNines,
    KingsAndEights,
    KingsAndSevens,
    KingsAndSixes,
    KingsAndFives,
    KingsAndFours,
    KingsAndTreys,
    KingsAndDeuces,
    QueensAndJacks,
    QueensAndTens,
    QueensAndNines,
    QueensAndEights,
    QueensAndSevens,
    QueensAndSixes,
    QueensAndFives,
    QueensAndFours,
    QueensAndTreys,
    QueensAndDeuces,
    JacksAndTens,
    JacksAndNines,
    JacksAndEights,
    JacksAndSevens,
    JacksAndSixes,
    JacksAndFives,
    JacksAndFours,
    JacksAndTreys,
    JacksAndDeuces,
    TensAndNines,
    TensAndEights,
    TensAndSevens,
    TensAndSixes,
    TensAndFives,
    TensAndFours,
    TensAndTreys,
    TensAndDeuces,
    NinesAndEights,
    NinesAndSevens,
    NinesAndSixes,
    NinesAndFives,
    NinesAndFours,
    NinesAndTreys,
    NinesAndDeuces,
    EightsAndSevens,
    EightsAndSixes,
    EightsAndFives,
    EightsAndFours,
    EightsAndTreys,
    EightsAndDeuces,
    SevensAndSixes,
    SevensAndFives,
    SevensAndFours,
    SevensAndTreys,
    SevensAndDeuces,
    SixesAndFives,
    SixesAndFours,
    SixesAndTreys,
    SixesAndDeuces,
    FivesAndFours,
    FivesAndTreys,
    FivesAndDeuces,
    FoursAndTreys,
    FoursAndDeuces,
    TreysAndDeuces,
    PairOfAces,
    PairOfKings,
    PairOfQueens,
    PairOfJacks,
    PairOfTens,
    PairOfNines,
    PairOfEights,
    PairOfSevens,
    PairOfSixes,
    PairOfFives,
    PairOfFours,
    PairOfTreys,
    PairOfDeuces,
    AceHigh,
    KingHigh,
    QueenHigh,
    JackHigh,
    TenHigh,
    NineHigh,
    EightHigh,
    SevenHigh,
    Invalid,
}

impl Default for Class {
    fn default() -> Self {
        Class::Invalid
    }
}

#[allow(clippy::too_many_lines)]
impl From<HandRankValue> for Class {
    fn from(hrv: HandRankValue) -> Self {
        match hrv {
            1 => Class::RoyalFlush,
            2 => Class::KingHighStraightFlush,
            3 => Class::QueenHighStraightFlush,
            4 => Class::JackHighStraightFlush,
            5 => Class::TenHighStraightFlush,
            6 => Class::NineHighStraightFlush,
            7 => Class::EightHighStraightFlush,
            8 => Class::SevenHighStraightFlush,
            9 => Class::SixHighStraightFlush,
            10 => Class::FiveHighStraightFlush,
            11..=22 => Class::FourAces,
            23..=34 => Class::FourKings,
            35..=46 => Class::FourQueens,
            47..=58 => Class::FourJacks,
            59..=70 => Class::FourTens,
            71..=82 => Class::FourNines,
            83..=94 => Class::FourEights,
            95..=106 => Class::FourSevens,
            107..=118 => Class::FourSixes,
            119..=130 => Class::FourFives,
            131..=142 => Class::FourFours,
            143..=154 => Class::FourTreys,
            155..=166 => Class::FourDeuces,
            167 => Class::AcesOverKings,
            168 => Class::AcesOverQueens,
            169 => Class::AcesOverJacks,
            170 => Class::AcesOverTens,
            171 => Class::AcesOverNines,
            172 => Class::AcesOverEights,
            173 => Class::AcesOverSevens,
            174 => Class::AcesOverSixes,
            175 => Class::AcesOverFives,
            176 => Class::AcesOverFours,
            177 => Class::AcesOverTreys,
            178 => Class::AcesOverDeuces,
            179 => Class::KingsOverAces,
            180 => Class::KingsOverQueens,
            181 => Class::KingsOverJacks,
            182 => Class::KingsOverTens,
            183 => Class::KingsOverNines,
            184 => Class::KingsOverEights,
            185 => Class::KingsOverSevens,
            186 => Class::KingsOverSixes,
            187 => Class::KingsOverFives,
            188 => Class::KingsOverFours,
            189 => Class::KingsOverTreys,
            190 => Class::KingsOverDeuces,
            191 => Class::QueensOverAces,
            192 => Class::QueensOverKings,
            193 => Class::QueensOverJacks,
            194 => Class::QueensOverTens,
            195 => Class::QueensOverNines,
            196 => Class::QueensOverEights,
            197 => Class::QueensOverSevens,
            198 => Class::QueensOverSixes,
            199 => Class::QueensOverFives,
            200 => Class::QueensOverFours,
            201 => Class::QueensOverTreys,
            202 => Class::QueensOverDeuces,
            203 => Class::JacksOverAces,
            204 => Class::JacksOverKings,
            205 => Class::JacksOverQueens,
            206 => Class::JacksOverTens,
            207 => Class::JacksOverNines,
            208 => Class::JacksOverEights,
            209 => Class::JacksOverSevens,
            210 => Class::JacksOverSixes,
            211 => Class::JacksOverFives,
            212 => Class::JacksOverFours,
            213 => Class::JacksOverTreys,
            214 => Class::JacksOverDeuces,
            215 => Class::TensOverAces,
            216 => Class::TensOverKings,
            217 => Class::TensOverQueens,
            218 => Class::TensOverJacks,
            219 => Class::TensOverNines,
            220 => Class::TensOverEights,
            221 => Class::TensOverSevens,
            222 => Class::TensOverSixes,
            223 => Class::TensOverFives,
            224 => Class::TensOverFours,
            225 => Class::TensOverTreys,
            226 => Class::TensOverDeuces,
            227 => Class::NinesOverAces,
            228 => Class::NinesOverKings,
            229 => Class::NinesOverQueens,
            230 => Class::NinesOverJacks,
            231 => Class::NinesOverTens,
            232 => Class::NinesOverEights,
            233 => Class::NinesOverSevens,
            234 => Class::NinesOverSixes,
            235 => Class::NinesOverFives,
            236 => Class::NinesOverFours,
            237 => Class::NinesOverTreys,
            238 => Class::NinesOverDeuces,
            239 => Class::EightsOverAces,
            240 => Class::EightsOverKings,
            241 => Class::EightsOverQueens,
            242 => Class::EightsOverJacks,
            243 => Class::EightsOverTens,
            244 => Class::EightsOverNines,
            245 => Class::EightsOverSevens,
            246 => Class::EightsOverSixes,
            247 => Class::EightsOverFives,
            248 => Class::EightsOverFours,
            249 => Class::EightsOverTreys,
            250 => Class::EightsOverDeuces,
            251 => Class::SevensOverAces,
            252 => Class::SevensOverKings,
            253 => Class::SevensOverQueens,
            254 => Class::SevensOverJacks,
            255 => Class::SevensOverTens,
            256 => Class::SevensOverNines,
            257 => Class::SevensOverEights,
            258 => Class::SevensOverSixes,
            259 => Class::SevensOverFives,
            260 => Class::SevensOverFours,
            261 => Class::SevensOverTreys,
            262 => Class::SevensOverDeuces,
            263 => Class::SixesOverAces,
            264 => Class::SixesOverKings,
            265 => Class::SixesOverQueens,
            266 => Class::SixesOverJacks,
            267 => Class::SixesOverTens,
            268 => Class::SixesOverNines,
            269 => Class::SixesOverEights,
            270 => Class::SixesOverSevens,
            271 => Class::SixesOverFives,
            272 => Class::SixesOverFours,
            273 => Class::SixesOverTreys,
            274 => Class::SixesOverDeuces,
            275 => Class::FivesOverAces,
            276 => Class::FivesOverKings,
            277 => Class::FivesOverQueens,
            278 => Class::FivesOverJacks,
            279 => Class::FivesOverTens,
            280 => Class::FivesOverNines,
            281 => Class::FivesOverEights,
            282 => Class::FivesOverSevens,
            283 => Class::FivesOverSixes,
            284 => Class::FivesOverFours,
            285 => Class::FivesOverTreys,
            286 => Class::FivesOverDeuces,
            287 => Class::FoursOverAces,
            288 => Class::FoursOverKings,
            289 => Class::FoursOverQueens,
            290 => Class::FoursOverJacks,
            291 => Class::FoursOverTens,
            292 => Class::FoursOverNines,
            293 => Class::FoursOverEights,
            294 => Class::FoursOverSevens,
            295 => Class::FoursOverSixes,
            296 => Class::FoursOverFives,
            297 => Class::FoursOverTreys,
            298 => Class::FoursOverDeuces,
            299 => Class::TreysOverAces,
            300 => Class::TreysOverKings,
            301 => Class::TreysOverQueens,
            302 => Class::TreysOverJacks,
            303 => Class::TreysOverTens,
            304 => Class::TreysOverNines,
            305 => Class::TreysOverEights,
            306 => Class::TreysOverSevens,
            307 => Class::TreysOverSixes,
            308 => Class::TreysOverFives,
            309 => Class::TreysOverFours,
            310 => Class::TreysOverDeuces,
            311 => Class::DeucesOverAces,
            312 => Class::DeucesOverKings,
            313 => Class::DeucesOverQueens,
            314 => Class::DeucesOverJacks,
            315 => Class::DeucesOverTens,
            316 => Class::DeucesOverNines,
            317 => Class::DeucesOverEights,
            318 => Class::DeucesOverSevens,
            319 => Class::DeucesOverSixes,
            320 => Class::DeucesOverFives,
            321 => Class::DeucesOverFours,
            322 => Class::DeucesOverTreys,
            323..=815 => Class::AceHighFlush,
            816..=1144 => Class::KingHighFlush,
            1145..=1353 => Class::QueenHighFlush,
            1354..=1478 => Class::JackHighFlush,
            1479..=1547 => Class::TenHighFlush,
            1548..=1581 => Class::NineHighFlush,
            1582..=1595 => Class::EightHighFlush,
            1596..=1599 => Class::SevenHighFlush,
            1600 => Class::AceHighStraight,
            1601 => Class::KingHighStraight,
            1602 => Class::QueenHighStraight,
            1603 => Class::JackHighStraight,
            1604 => Class::TenHighStraight,
            1605 => Class::NineHighStraight,
            1606 => Class::EightHighStraight,
            1607 => Class::SevenHighStraight,
            1608 => Class::SixHighStraight,
            1609 => Class::FiveHighStraight,
            1610..=1675 => Class::ThreeAces,
            1676..=1741 => Class::ThreeKings,
            1742..=1807 => Class::ThreeQueens,
            1808..=1873 => Class::ThreeJacks,
            1874..=1939 => Class::ThreeTens,
            1940..=2005 => Class::ThreeNines,
            2006..=2071 => Class::ThreeEights,
            2072..=2137 => Class::ThreeSevens,
            2138..=2203 => Class::ThreeSixes,
            2204..=2269 => Class::ThreeFives,
            2270..=2335 => Class::ThreeFours,
            2336..=2401 => Class::ThreeTreys,
            2402..=2467 => Class::ThreeDeuces,
            2468..=2478 => Class::AcesAndKings,
            2479..=2489 => Class::AcesAndQueens,
            2490..=2500 => Class::AcesAndJacks,
            2501..=2511 => Class::AcesAndTens,
            2512..=2522 => Class::AcesAndNines,
            2523..=2533 => Class::AcesAndEights,
            2534..=2544 => Class::AcesAndSevens,
            2545..=2555 => Class::AcesAndSixes,
            2556..=2566 => Class::AcesAndFives,
            2567..=2577 => Class::AcesAndFours,
            2578..=2588 => Class::AcesAndTreys,
            2589..=2599 => Class::AcesAndDeuces,
            2600..=2610 => Class::KingsAndQueens,
            2611..=2621 => Class::KingsAndJacks,
            2622..=2632 => Class::KingsAndTens,
            2633..=2643 => Class::KingsAndNines,
            2644..=2654 => Class::KingsAndEights,
            2655..=2665 => Class::KingsAndSevens,
            2666..=2676 => Class::KingsAndSixes,
            2677..=2687 => Class::KingsAndFives,
            2688..=2698 => Class::KingsAndFours,
            2699..=2709 => Class::KingsAndTreys,
            2710..=2720 => Class::KingsAndDeuces,
            2721..=2731 => Class::QueensAndJacks,
            2732..=2742 => Class::QueensAndTens,
            2743..=2753 => Class::QueensAndNines,
            2754..=2764 => Class::QueensAndEights,
            2765..=2775 => Class::QueensAndSevens,
            2776..=2786 => Class::QueensAndSixes,
            2787..=2797 => Class::QueensAndFives,
            2798..=2808 => Class::QueensAndFours,
            2809..=2819 => Class::QueensAndTreys,
            2820..=2830 => Class::QueensAndDeuces,
            2831..=2841 => Class::JacksAndTens,
            2842..=2852 => Class::JacksAndNines,
            2853..=2863 => Class::JacksAndEights,
            2864..=2874 => Class::JacksAndSevens,
            2875..=2885 => Class::JacksAndSixes,
            2886..=2896 => Class::JacksAndFives,
            2897..=2907 => Class::JacksAndFours,
            2908..=2918 => Class::JacksAndTreys,
            2919..=2929 => Class::JacksAndDeuces,
            2930..=2940 => Class::TensAndNines,
            2941..=2951 => Class::TensAndEights,
            2952..=2962 => Class::TensAndSevens,
            2963..=2973 => Class::TensAndSixes,
            2974..=2984 => Class::TensAndFives,
            2985..=2995 => Class::TensAndFours,
            2996..=3006 => Class::TensAndTreys,
            3007..=3017 => Class::TensAndDeuces,
            3018..=3028 => Class::NinesAndEights,
            3029..=3039 => Class::NinesAndSevens,
            3040..=3050 => Class::NinesAndSixes,
            3051..=3061 => Class::NinesAndFives,
            3062..=3072 => Class::NinesAndFours,
            3073..=3083 => Class::NinesAndTreys,
            3084..=3094 => Class::NinesAndDeuces,
            3095..=3105 => Class::EightsAndSevens,
            3106..=3116 => Class::EightsAndSixes,
            3117..=3127 => Class::EightsAndFives,
            3128..=3138 => Class::EightsAndFours,
            3139..=3149 => Class::EightsAndTreys,
            3150..=3160 => Class::EightsAndDeuces,
            3161..=3171 => Class::SevensAndSixes,
            3172..=3182 => Class::SevensAndFives,
            3183..=3193 => Class::SevensAndFours,
            3194..=3204 => Class::SevensAndTreys,
            3205..=3215 => Class::SevensAndDeuces,
            3216..=3226 => Class::SixesAndFives,
            3227..=3237 => Class::SixesAndFours,
            3238..=3248 => Class::SixesAndTreys,
            3249..=3259 => Class::SixesAndDeuces,
            3260..=3270 => Class::FivesAndFours,
            3271..=3281 => Class::FivesAndTreys,
            3282..=3292 => Class::FivesAndDeuces,
            3293..=3303 => Class::FoursAndTreys,
            3304..=3314 => Class::FoursAndDeuces,
            3315..=3325 => Class::TreysAndDeuces,
            3326..=3545 => Class::PairOfAces,
            3546..=3765 => Class::PairOfKings,
            3766..=3985 => Class::PairOfQueens,
            3986..=4205 => Class::PairOfJacks,
            4206..=4425 => Class::PairOfTens,
            4426..=4645 => Class::PairOfNines,
            4646..=4865 => Class::PairOfEights,
            4866..=5085 => Class::PairOfSevens,
            5086..=5305 => Class::PairOfSixes,
            5306..=5525 => Class::PairOfFives,
            5526..=5745 => Class::PairOfFours,
            5746..=5965 => Class::PairOfTreys,
            5966..=6185 => Class::PairOfDeuces,
            6186..=6678 => Class::AceHigh,
            6679..=7007 => Class::KingHigh,
            7008..=7216 => Class::QueenHigh,
            7217..=7341 => Class::JackHigh,
            7342..=7410 => Class::TenHigh,
            7411..=7444 => Class::NineHigh,
            7445..=7458 => Class::EightHigh,
            7459..=7462 => Class::SevenHigh,
            _ => Class::Invalid,
        }
    }
}

impl SOK for Class {
    fn salright(&self) -> bool {
        self != &Class::Invalid
    }
}

#[cfg(test)]
#[allow(non_snake_case)]
mod hand_rank__class_tests {
    use super::*;

    #[test]
    fn salright() {
        assert!(Class::AcesOverQueens.salright());
        assert!(!Class::Invalid.salright());
    }
}
