//! Renders committed results files as a markdown table.
//!
//! Phase 1 emits one section per run. The native/wasmtime/browser ratio column
//! arrives in Phase 4, once there is more than one runtime to compare.

use crate::results::Results;
use std::fmt::Write;

/// Renders every run as markdown, newest sections last.
///
/// # Examples
///
/// ```
/// use pkcore_perf::report::render;
///
/// assert!(render(&[]).contains("No results"));
/// ```
#[must_use]
pub fn render(runs: &[Results]) -> String {
    let mut out = String::new();
    out.push_str("# pkcore Performance Results\n\n");
    out.push_str(
        "Generated by `make perf-report`. Do not edit by hand.\n\
         Figures are nanoseconds per operation. `min` is the best estimator of \
         true cost in the nano band; `MAD` is the median absolute deviation \
         from the median.\n\n",
    );

    if runs.is_empty() {
        out.push_str("No results recorded yet. Run `make perf-native`.\n");
        return out;
    }

    for run in runs {
        let features = if run.run.features.is_empty() {
            "pure-kernel".to_string()
        } else {
            run.run.features.join(", ")
        };
        let cores = match (run.run.host.p_cores, run.run.host.e_cores) {
            (Some(p), Some(e)) => format!("{} cores ({p}P + {e}E)", run.run.host.cores),
            _ => format!("{} cores", run.run.host.cores),
        };

        let _ = writeln!(out, "## {} — {}", run.run.target, run.run.runtime);
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "**Host:** {} · {cores}  \n\
             **Features:** {features}  \n\
             **pkcore:** {} · **{}**  \n\
             **Taken:** {}",
            run.run.host.cpu, run.run.pkcore, run.run.rustc, run.run.utc
        );
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "| Workload | Band | median | min | p95 | MAD | checksum | status |"
        );
        let _ = writeln!(out, "|---|---|---:|---:|---:|---:|---|---|");

        for sample in &run.samples {
            let checksum = sample.checksum.map_or_else(|| "—".to_string(), |c| format!("`{c}`"));
            let status = format!("{:?}", sample.status).to_lowercase();

            match sample.ns_per_op {
                Some(stats) => {
                    let _ = writeln!(
                        out,
                        "| `{}` | {:?} | {:.2} | {:.2} | {:.2} | {:.2} | {checksum} | {status} |",
                        sample.name, sample.band, stats.median, stats.min, stats.p95, stats.mad
                    );
                }
                None => {
                    let _ = writeln!(
                        out,
                        "| `{}` | {:?} | — | — | — | — | {checksum} | {status} |",
                        sample.name, sample.band
                    );
                }
            }
        }
        let _ = writeln!(out);
    }

    out
}

#[cfg(test)]
#[allow(non_snake_case)]
mod perf__report_tests {
    use super::*;
    use crate::results::Results;

    fn fixture() -> Results {
        let raw = include_str!("../tests/fixtures/sample-results.json");
        serde_json::from_str(raw).expect("fixture parses")
    }

    #[test]
    fn render_includes_a_row_per_workload() {
        let markdown = render(&[fixture()]);
        assert!(markdown.contains("eval.five.hand_rank_value"));
        assert!(markdown.contains("eval.seven.hand_rank_value"));
    }

    #[test]
    fn render_reports_median_and_spread() {
        let markdown = render(&[fixture()]);
        assert!(markdown.contains("4.30"), "median missing: {markdown}");
        assert!(markdown.contains("4.90"), "p95 missing: {markdown}");
    }

    #[test]
    fn render_records_the_host_and_feature_context() {
        let markdown = render(&[fixture()]);
        assert!(markdown.contains("Apple M1"));
        assert!(markdown.contains("aarch64-apple-darwin"));
        assert!(markdown.contains("pure-kernel"));
        assert!(markdown.contains("0.3.2"));
    }

    #[test]
    fn render_handles_no_runs() {
        let markdown = render(&[]);
        assert!(markdown.contains("No results"));
    }
}
