//! Renders committed results files as a markdown table.
//!
//! Phase 1 emits one section per run. The native/wasmtime/browser ratio column
//! arrives in Phase 4, once there is more than one runtime to compare.

use crate::results::Results;
use std::fmt::Write;

/// Renders every run as markdown, newest sections last.
///
/// # Examples
///
/// ```
/// use pkcore_perf::report::render;
///
/// assert!(render(&[]).contains("No results"));
/// ```
#[must_use]
pub fn render(runs: &[Results]) -> String {
    let mut out = String::new();
    out.push_str("# pkcore Performance Results\n\n");
    out.push_str(
        "Generated by `make perf-report`. Do not edit by hand.\n\
         Figures are nanoseconds per operation. `min` is the best estimator of \
         true cost in the nano band; `MAD` is the median absolute deviation \
         from the median.\n\n",
    );

    if runs.is_empty() {
        out.push_str("No results recorded yet. Run `make perf-native`.\n");
        return out;
    }

    for run in runs {
        let features = if run.run.features.is_empty() {
            "pure-kernel".to_string()
        } else {
            run.run.features.join(", ")
        };
        let cores = match (run.run.host.p_cores, run.run.host.e_cores) {
            (Some(p), Some(e)) => format!("{} cores ({p}P + {e}E)", run.run.host.cores),
            _ => format!("{} cores", run.run.host.cores),
        };

        match &run.run.label {
            Some(label) => {
                let _ = writeln!(out, "## {} — {} ({label})", run.run.target, run.run.runtime);
            }
            None => {
                let _ = writeln!(out, "## {} — {}", run.run.target, run.run.runtime);
            }
        }
        let _ = writeln!(out);
        let label_line = run.run.label.as_deref().unwrap_or("—");
        let _ = writeln!(
            out,
            "**Host:** {} · {cores}  \n\
             **Features:** {features}  \n\
             **Label:** {label_line}  \n\
             **pkcore:** {} · **{}**  \n\
             **Taken:** {}",
            run.run.host.cpu, run.run.pkcore, run.run.rustc, run.run.utc
        );
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "| Workload | Band | threads | median | min | p95 | MAD | checksum | status |"
        );
        let _ = writeln!(out, "|---|---|---:|---:|---:|---:|---:|---|---|");

        for sample in &run.samples {
            let checksum = sample.checksum.map_or_else(|| "—".to_string(), |c| format!("`{c}`"));
            let status = format!("{:?}", sample.status).to_lowercase();
            let threads = sample.rayon_threads.map_or_else(|| "—".to_string(), |t| t.to_string());

            match sample.ns_per_op {
                Some(stats) => {
                    let _ = writeln!(
                        out,
                        "| `{}` | {:?} | {threads} | {:.2} | {:.2} | {:.2} | {:.2} | {checksum} | {status} |",
                        sample.name, sample.band, stats.median, stats.min, stats.p95, stats.mad
                    );
                }
                None => {
                    let _ = writeln!(
                        out,
                        "| `{}` | {:?} | {threads} | — | — | — | — | {checksum} | {status} |",
                        sample.name, sample.band
                    );
                }
            }
        }
        let _ = writeln!(out);
    }

    out
}

#[cfg(test)]
#[allow(non_snake_case)]
mod perf__report_tests {
    use super::*;
    use crate::results::Results;

    fn fixture() -> Results {
        let raw = include_str!("../tests/fixtures/sample-results.json");
        serde_json::from_str(raw).expect("fixture parses")
    }

    #[test]
    fn render_includes_a_row_per_workload() {
        let markdown = render(&[fixture()]);
        assert!(markdown.contains("eval.five.hand_rank_value"));
        assert!(markdown.contains("eval.seven.hand_rank_value"));
    }

    #[test]
    fn render_reports_median_and_spread() {
        let markdown = render(&[fixture()]);
        assert!(markdown.contains("4.30"), "median missing: {markdown}");
        assert!(markdown.contains("4.90"), "p95 missing: {markdown}");
    }

    #[test]
    fn render_records_the_host_and_feature_context() {
        let markdown = render(&[fixture()]);
        assert!(markdown.contains("Apple M1"));
        assert!(markdown.contains("aarch64-apple-darwin"));
        assert!(markdown.contains("pure-kernel"));
        assert!(markdown.contains("0.3.2"));
    }

    #[test]
    fn render_handles_no_runs() {
        let markdown = render(&[]);
        assert!(markdown.contains("No results"));
    }

    /// `RESULTS.md` commits several runs for the same target and date (e.g.
    /// the pure-kernel run and an all-features run taken minutes apart); the
    /// timestamp alone does not read as a difference at a glance. The label
    /// must show up both in the section heading, so scanning the table of
    /// contents distinguishes them, and in the metadata block.
    #[test]
    fn render_distinguishes_labelled_runs_in_the_heading_and_metadata() {
        let mut labelled = fixture();
        labelled.run.label = Some("all-features".to_string());

        let markdown = render(&[labelled]);
        assert!(
            markdown.contains("## aarch64-apple-darwin — native (all-features)"),
            "label missing from heading: {markdown}"
        );
        assert!(
            markdown.contains("**Label:** all-features"),
            "label missing from metadata: {markdown}"
        );
    }

    #[test]
    fn render_shows_no_label_placeholder_when_absent() {
        let markdown = render(&[fixture()]);
        assert!(markdown.contains("**Label:** —"), "expected placeholder: {markdown}");
        assert!(
            markdown.contains("## aarch64-apple-darwin — native\n"),
            "unlabelled heading should carry no suffix: {markdown}"
        );
    }
}
