#![doc = include_str!("BOT_MODULE_GUIDE.md")]

pub mod betting_strategy;
pub mod decider;
pub mod decision_config;
pub mod draw_equity;
#[cfg(feature = "player-stats")]
pub mod exploit;
#[cfg(feature = "player-stats")]
pub mod exploitative_decider;
pub mod hand_order;
pub mod playbook;
pub mod player_action;
pub mod position_ranges;
pub mod positional_betting;
pub mod preflop_equity;
pub mod profile;
pub mod range_model;
pub mod range_strategy;
pub mod sim;
pub mod table_size;
pub mod table_snapshot;
#[cfg(feature = "bot-training")]
pub mod training;
pub mod weighted_range;
