//! Replay a saved interactive-play session from a YAML hand-history file.
//!
//! Loads a [`HandCollection`] YAML file (generated by `interactive_play`),
//! displays every hand street-by-street with all hole cards visible, and
//! validates each hand's recorded actions against the game engine via
//! [`HandHistory::replay`].
//!
//! **Usage:**
//! ```text
//! # replay most recent file in generated/
//! cargo run --features hand-histories --example replay_play
//!
//! # replay a specific file
//! cargo run --features hand-histories --example replay_play -- generated/interactive_play_1234567890.yaml
//! ```
//!
//! When running in a terminal the viewer pauses between hands. Pipe the output
//! or redirect to a file to print all hands without pausing.

use pkcore::hand_history::{Action, ActionType, HandCollection, HandHistory, PlayerEntry, ResultEntry};
use std::io::{self, IsTerminal, Write};
use std::path::PathBuf;

fn main() {
    let path = resolve_path();
    let yaml = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        eprintln!("error: cannot read {}: {e}", path.display());
        std::process::exit(1);
    });
    let collection = HandCollection::from_yaml(&yaml).unwrap_or_else(|e| {
        eprintln!("error: cannot parse YAML in {}: {e}", path.display());
        std::process::exit(1);
    });

    println!("=== Replay: {}  ({} hand(s)) ===", path.display(), collection.len());
    if let Some(ver) = collection.pkcore_version.as_str().split('+').next() {
        println!("    pkcore {}  format v{}", ver, collection.format_version);
    }
    println!();

    let is_tty = io::stdin().is_terminal();

    for (idx, hand) in collection.hands().iter().enumerate() {
        print_hand(hand);

        // Validate via replay engine.
        match hand.replay() {
            Ok(result) => {
                if result.is_consistent {
                    println!("  ✓ replay consistent");
                } else {
                    println!("  ✗ MISMATCH — recorded results don't match replayed chip counts");
                    for (seat, chips) in &result.final_stacks {
                        println!("      seat {seat}: {chips} chips (replayed)");
                    }
                }
            }
            Err(e) => println!("  ✗ replay error: {e}"),
        }

        if is_tty && idx + 1 < collection.len() {
            print!("\n  --- press Enter for next hand (q to quit) --- ");
            io::stdout().flush().ok();
            let mut line = String::new();
            io::stdin().read_line(&mut line).ok();
            if line.trim().eq_ignore_ascii_case("q") {
                println!("Stopped at hand {}.", idx + 1);
                return;
            }
        }
        println!();
    }

    println!("=== End of session ===");
}

// ── Display ────────────────────────────────────────────────────────────────────

fn print_hand(hand: &HandHistory) {
    // Header
    let btn = hand
        .table
        .button
        .map(|b| b.to_string())
        .unwrap_or_else(|| "?".to_string());
    let ts = hand.hand.timestamp.as_deref().unwrap_or("");
    println!(
        "─── {}  btn={}  blinds={}/{}  {} ───",
        hand.hand.id, btn, hand.table.stakes.small_blind as usize, hand.table.stakes.big_blind as usize, ts,
    );

    // Starting stacks + hole cards
    println!("  Seat  Name                    Stack  Hole cards");
    for p in &hand.players {
        let hole = p.hole_cards.as_deref().unwrap_or("??");
        println!("  {:>4}  {:<22}  {:>6}  {}", p.seat, p.name, p.stack as usize, hole);
    }
    println!();

    let Some(ref streets) = hand.streets else {
        println!("  (no street data)");
        return;
    };

    // Preflop
    if let Some(ref pre) = streets.preflop {
        print!("  Preflop");
        if let Some(pot) = pre.pot {
            print!("  [pot: {}]", pot as usize);
        }
        println!();
        for action in &pre.actions {
            println!("    {}", format_action(action, &hand.players));
        }
    }

    // Flop
    if let Some(ref flop) = streets.flop {
        print!("  Flop: {}  ", flop.cards);
        if let Some(pot) = flop.pot {
            print!("[pot: {}]", pot as usize);
        }
        println!();
        for action in &flop.actions {
            println!("    {}", format_action(action, &hand.players));
        }
    }

    // Turn
    if let Some(ref turn) = streets.turn {
        print!("  Turn: {}  ", turn.card);
        if let Some(pot) = turn.pot {
            print!("[pot: {}]", pot as usize);
        }
        println!();
        for action in &turn.actions {
            println!("    {}", format_action(action, &hand.players));
        }
    }

    // River
    if let Some(ref river) = streets.river {
        print!("  River: {}  ", river.card);
        if let Some(pot) = river.pot {
            print!("[pot: {}]", pot as usize);
        }
        println!();
        for action in &river.actions {
            println!("    {}", format_action(action, &hand.players));
        }
    }

    // Board summary
    if let Some(ref board) = hand.board {
        println!("  Board: {board}");
    }

    // Results
    if let Some(ref results) = hand.results {
        println!("  Results:");
        for r in results {
            println!("    {}", format_result(r, &hand.players));
        }
    }
}

fn format_action(action: &Action, players: &[PlayerEntry]) -> String {
    let name = player_name(action.seat, players);
    let verb = match action.action {
        ActionType::Post => format!("posts {}", action.amount.map(|a| a as usize).unwrap_or(0)),
        ActionType::Fold => "folds".to_string(),
        ActionType::Check => "checks".to_string(),
        ActionType::Call => format!("calls {}", action.amount.map(|a| a as usize).unwrap_or(0)),
        ActionType::Bet => format!("bets {}", action.amount.map(|a| a as usize).unwrap_or(0)),
        ActionType::Raise => format!("raises to {}", action.amount.map(|a| a as usize).unwrap_or(0)),
        ActionType::AllIn => format!("ALL-IN ({})", action.amount.map(|a| a as usize).unwrap_or(0)),
    };
    let ai = if action.all_in == Some(true) { " [all-in]" } else { "" };
    format!("{name:<22}  {verb}{ai}")
}

fn format_result(r: &ResultEntry, players: &[PlayerEntry]) -> String {
    let name = player_name(r.seat, players);
    let outcome = format!("{:?}", r.outcome).to_lowercase();
    let net = r.net.map(|n| format!("{n:+.0}")).unwrap_or_default();
    let hand = r.best_hand.as_deref().unwrap_or("");
    format!("{name:<22}  {outcome:<5}  net={net:>7}  {hand}")
}

fn player_name<'a>(seat: u8, players: &'a [PlayerEntry]) -> &'a str {
    players
        .iter()
        .find(|p| p.seat == seat)
        .map(|p| p.name.as_str())
        .unwrap_or("?")
}

// ── File resolution ────────────────────────────────────────────────────────────

fn resolve_path() -> PathBuf {
    if let Some(arg) = std::env::args().nth(1) {
        return PathBuf::from(arg);
    }
    most_recent_yaml("generated").unwrap_or_else(|| {
        eprintln!("error: no YAML files found in generated/ and no path argument given.");
        eprintln!("  Run `cargo run --example interactive_play` first to generate a session.");
        std::process::exit(1);
    })
}

fn most_recent_yaml(dir: &str) -> Option<PathBuf> {
    let entries = std::fs::read_dir(dir).ok()?;
    entries
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "yaml"))
        .filter_map(|e| {
            let mtime = e.metadata().ok()?.modified().ok()?;
            Some((mtime, e.path()))
        })
        .max_by_key(|(mtime, _)| *mtime)
        .map(|(_, path)| path)
}

// ── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use pkcore::hand_history::PlayerEntry;

    fn make_players() -> Vec<PlayerEntry> {
        vec![
            PlayerEntry {
                seat: 0,
                player_id: None,
                name: "Alice".to_string(),
                stack: 1000.0,
                hole_cards: None,
                posted: None,
            },
            PlayerEntry {
                seat: 1,
                player_id: None,
                name: "Bob".to_string(),
                stack: 1000.0,
                hole_cards: None,
                posted: None,
            },
        ]
    }

    #[test]
    fn test_player_name_found() {
        let players = make_players();
        assert_eq!(player_name(0, &players), "Alice");
        assert_eq!(player_name(1, &players), "Bob");
    }

    #[test]
    fn test_player_name_fallback() {
        let players = make_players();
        assert_eq!(player_name(9, &players), "?");
    }

    #[test]
    fn test_most_recent_yaml_missing_dir() {
        assert!(most_recent_yaml("/nonexistent/dir").is_none());
    }
}
